### ISSUE TITLE
Determine if ConfigureWithOutputs is sufficient for beatreceiver project

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent-libs#225]
https://github.com/elastic/elastic-agent-libs/pull/218 proposes a new function `ConfigureWithCore`, but `ConfigureWithOutputs` already exists.

Need to determine if existing `ConfigureWithOutputs` is sufficient or could be modified to work with beats receiver project.

**Comment by leehinman** [comment]
In its current form [ConfigureWithOutputs](https://github.com/elastic/elastic-agent-libs/blob/5104a902304586d07906b91e169983699fa46d82/logp/core.go#L137) calls [createSink](https://github.com/elastic/elastic-agent-libs/blob/5104a902304586d07906b91e169983699fa46d82/logp/core.go#L83) which creates a new [logOutput](https://github.com/elastic/elastic-agent-libs/blob/5104a902304586d07906b91e169983699fa46d82/logp/core.go#L96).  This isn't what we want in the case of the beats receivers.  We don't want to setup file logging, all of the log retention should be handled already.  In #218 we are calling [wrappedCore](https://github.com/elastic/elastic-agent-libs/blob/5104a902304586d07906b91e169983699fa46d82/logp/core.go#L346) to get the new sink, and [selectiveWrapper](https://github.com/elastic/elastic-agent-libs/blob/5104a902304586d07906b91e169983699fa46d82/logp/selective.go#L38) to set the selectors on it.  

@belimawr we could change `ConfigureWithOutputs` so if toObserver, toIODiscard, ToStderr, ToSyslog, ToFiles, and ToEventLog were all false it it didn't call `createSink` but instead used `wrappedCore`.  What do you think?

**Comment by belimawr** [comment]
> [@belimawr](https://github.com/belimawr) we could change `ConfigureWithOutputs` so if toObserver, toIODiscard, ToStderr, ToSyslog, ToFiles, and ToEventLog were all false it it didn't call `createSink` but instead used `wrappedCore`. What do you think?

I'm not a fan of this "magic behaviour". But first things first, let me truly understand your goal here.

Because of the Beats receiver project, we need to be able to take an already existing `zapcore.Core` and use it without ever creating a new one, is that it? Effectively an empty `logp.Config` will not create any output, is that it?

I'm not a huge fan of "magic behaviour", but it seems to make sense and I believe we have enough tests in place to avoid unforeseen side effects like https://github.com/elastic/elastic-agent-libs/pull/208 fixed. `logp.DefaultConfig` setting `ToFiles` seems to make sense with this new proposed behaviour.

Just make sure to document it in `ConfigureWithOutputs` and test a standalone Beat to ensure the current behaviour is not changed.

**Comment by leehinman** [comment]
> Because of the Beats receiver project, we need to be able to take an already existing zapcore.Core and use it without ever creating a new one, is that it?

Essentially yes, the core is already configured with where the logs will be written to.  So we just want to use that, and potentially have selectors.

> I'm not a huge fan of "magic behaviour", but it seems to make sense and I believe we have enough tests in place to avoid unforeseen side effects like [#208](https://github.com/elastic/elastic-agent-libs/pull/208) fixed. `logp.DefaultConfig` setting `ToFiles` seems to make sense with this new proposed behaviour.

The avoiding magic was part of why I had a different function before.  In general I would prefer the new function.

**Comment by leehinman** [comment]
@belimawr  https://github.com/elastic/elastic-agent-libs/pull/218 is back out of Draft and ready for review
